# Generated by Django 4.1.2 on 2022-11-21 05:46

import DbOperationsApp.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Street1', models.CharField(max_length=200)),
                ('Street2', models.CharField(blank=True, max_length=200)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('Type', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=200)),
                ('PocName', models.CharField(blank=True, max_length=200)),
                ('Address', djongo.models.fields.EmbeddedField(model_container=DbOperationsApp.models.Address)),
                ('Contact', models.BigIntegerField(blank=True)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DonorRequest',
            fields=[
                ('RequestId', models.AutoField(primary_key=True, serialize=False)),
                ('DonationType', models.CharField(max_length=100)),
                ('DonationQty', models.TextField()),
                ('DonationAllergies', models.TextField(blank=True)),
                ('DonationDescription', models.TextField()),
                ('DonationPickupDate', models.DateField()),
                ('DonationPickupTime', models.TimeField()),
                ('DonorContact', models.BigIntegerField()),
                ('DonorAddress', djongo.models.fields.EmbeddedField(model_container=DbOperationsApp.models.Address)),
                ('DonationPhotoLink', models.URLField(blank=True)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbOperationsApp.donor')),
            ],
        ),
        migrations.CreateModel(
            name='DropOffLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationName', models.CharField(max_length=200)),
                ('LocationAddress', djongo.models.fields.EmbeddedField(model_container=DbOperationsApp.models.Address)),
                ('LocationContact', models.BigIntegerField(blank=True)),
                ('LocationHours', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('Type', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=200)),
                ('PocName', models.CharField(blank=True, max_length=200)),
                ('Address', djongo.models.fields.EmbeddedField(model_container=DbOperationsApp.models.Address)),
                ('Contact', models.BigIntegerField(blank=True)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestCreatedBy', models.EmailField(max_length=254)),
                ('RequestCreationDateTime', models.DateTimeField(auto_now=True)),
                ('RequestAcceptDateTime', models.DateTimeField(default=None)),
                ('RequestStatus', models.CharField(default='Active', max_length=20)),
                ('RequestAcceptedBy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DbOperationsApp.recipient')),
                ('RequestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbOperationsApp.donorrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RecipientLoginCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=30)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbOperationsApp.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='DonorLoginCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=30)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbOperationsApp.donor')),
            ],
        ),
    ]
