# Generated by Django 4.1.2 on 2022-11-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DbOperationsApp', '0002_rename_requeststatus_requeststatus_requestcurrentstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonorRequest',
            new_name='DonationRequest',
        ),
    ]
